CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_SECRET = ""

my_API = [ACCESS_TOKEN,ACCESS_SECRET,CONSUMER_KEY,CONSUMER_SECRET]

secrets = {
    'ACCESS_TOKEN' : ACCESS_TOKEN,
    'ACCESS_SECRET': ACCESS_SECRET,
    'CONSUMER_KEY':CONSUMER_KEY,
    'CONSUMER_SECRET':CONSUMER_SECRET
}